### ISSUE TITLE
Bug: Reaching passenger info page coming from AA doesn't show expected EQM 

### ISSUE THREAD

**Issue by agalli93** [heeshung/as-mileage-plan-earning-extension#2]
When proceeding to book on AA after having searched there, passenger details page doesn't show the expected EQM like it does when you reach the same page from google flights or ITA. May not need to be fixed if #1 gets implemented but just looks weird having the same page behave differently. 

From AA:
![image](https://user-images.githubusercontent.com/3828034/235321180-935d161c-de67-44df-9030-6cd2c69dee12.png)

From Google:
![image](https://user-images.githubusercontent.com/3828034/235321273-43ac5b80-9556-4c36-bb3d-369711d0bed4.png)

**Comment by heeshung** [comment]
Behavior as expected; not a bug.

**Comment by heeshung** [comment]
Behavior as expected; not a bug.
