### ISSUE TITLE
Bug: Selecting a J class or Y class AA fare through Google Flights doesn't predict EQM correctly. 

### ISSUE THREAD

**Issue by agalli93** [heeshung/as-mileage-plan-earning-extension#3]
When selecting a first class AA fare through Google Flights, the prediction is not giving a correct number of EQM. 

![image](https://user-images.githubusercontent.com/3828034/235321389-dfbe50cd-241e-4d83-9193-bd34226eb159.png)

Note that it is doing so correctly when using the details feature on the Trip Summary Page or Choose Flights page. 

![image](https://user-images.githubusercontent.com/3828034/235321381-34906fbc-03e5-4eac-a305-fe786abae2f7.png)

Could be a fare basis issue. The first class fare is showing fare basis of "NUAIZNIX" on the Passenger page as opposed to the details panes which have the correct booking code of I. Quick glance at the HTML and I don't see an easy way to get this to work except maybe a forcing function with the element "cabin_type : "F" " vs "C"  but there are two different earnings rates in business which may not work cleanly.

**Comment by agalli93** [comment]
Y class fare also failed coming from ITA.

![image](https://user-images.githubusercontent.com/3828034/235324051-add2444e-4d0d-4ed5-97cc-d03c5fa2fed5.png)

**Comment by heeshung** [comment]
fixed in commit 93f282e
